# Generated by Django 5.1.3 on 2024-11-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appt", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("add", models.CharField(max_length=50)),
                ("citizen", models.CharField(max_length=40)),
                ("mob", models.CharField(max_length=10)),
                ("marital", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "staff",
            },
        ),
    ]
